force-app/main/default/objects/ChildObject__c/ChildObject__c.object-meta.xml
<CustomObject>
    <label>ChildObject</label>
    <nameField>
        <label>ChidObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChildObjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChildObject__c/fields/TempObject__c.field-meta.xml
<CustomField>
    <fullName>TempObject__c</fullName>
    <label>TempObject</label>
    <referenceTo>TempObject__c</referenceTo>
    <relationshipLabel>ChildObjects</relationshipLabel>
    <relationshipName>ChildObjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TempObject__c/TempObject__c.object-meta.xml
<CustomObject>
    <label>TempObject</label>
    <nameField>
        <label>TempObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TempObjectsss</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SaveTempObject.cls
public class SaveTempObject {
    @AuraEnabled
    public static Id saveTempObjectDetails(TempObject__c tempObject){
        insert tempObject;
        return tempObject.Id;
    }
    
    @AuraEnabled
    public static Id saveChildObjDetails(ChildObject__c obj){
        insert obj;
        return obj.Id;
    }
    //1. Class name in Controller in Aura Conponent
    //2. var action = component.get("c.< Method Name >");
    //3. action.setParams({obj : chaildObj});
    //4. action.setCallback(this, function(a){
    //        a.getState();
    //        a.getReturnValue();
    //   });
    //   $A.enqueueAction(action);
}